In [1]:
#import pytorch library 
import torch

In [2]:
#check pytorch version installed
print(torch.__version__)

1.4.0


In [6]:
#create one 1-D tensor and print the shape and data
t1 = torch.tensor([1,2,3])
print(t.shape)
print(type(t))
print(t)

torch.Size([3])
<class 'torch.Tensor'>
tensor([1, 2, 3])


In [10]:
#create 2-D tensor and print the shape and elements
t2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t2.shape)
print(t2)

torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
#use of attribute shape and method size() for tensor
#o/p is the same
print(t2.shape)
print(t2.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [15]:
#printing rows and heights of the tensor
# print rows of the tensor t2
print('Rows of the tensor t2 -->')
print('using method size :{}'.format(str(t2.size(0))))
print('using attribute shape:{}'.format(str(t2.shape[0])))
#print heights of the tensor t2
print('Heights of the tensor t2 -->')
print('using method size :{}'.format(str(t2.size(1))))
print('using attribute shape:{}'.format(str(t2.shape[1])))
      

Rows of the tensor t2 -->
using method size :3
using attribute shape:3
Heights of the tensor t2 -->
using method size :3
using attribute shape:3


In [25]:
#create a float tensor
t3_float = torch.FloatTensor([[1,2,3.],[4.,5.,6.]])
print(t3_float)
print(t3_float.type())
#alternate approach 
t3_float = torch.tensor([[1.,2,3],[4.,5.,6.]],dtype=torch.float)
print(t3_float)
print(t3_float.type())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor


In [28]:
#create a double tensor
t4_double = torch.DoubleTensor([[1,2,3.],[4.,5.,6.]])
print(t4_double)
print(t4_double.type())
#alternate aproach
t4_double = torch.tensor([[1,2,3.],[4.,5.,6.]],dtype=torch.double)
print(t4_double)
print(t4_double.type())

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.DoubleTensor
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.DoubleTensor


In [29]:
#calculating mean and standard deviation
#calculate mean and standard devoation for t3_float and t4_double
print(t3_float.mean())
print(t3_float.std())
print(t4_double.mean())
print(t4_double.std())

tensor(3.5000)
tensor(1.8708)
tensor(3.5000, dtype=torch.float64)
tensor(1.8708, dtype=torch.float64)


In [30]:
#create 3-D tensor with random values
t5_3d = torch.randn(2,3,4) # creates metrix of shape 2x3x5 with random numbers having normal distribution
print(t5_3d.shape)
print(t5_3d)

torch.Size([2, 3, 4])
tensor([[[ 2.1491, -1.9523,  0.5236, -1.2723],
         [ 0.2671,  0.4847,  0.3938,  1.7444],
         [ 0.0934, -0.4298,  0.3893,  1.2825]],

        [[-0.0108, -0.6404,  1.2542,  1.4042],
         [ 0.3296, -0.2647, -0.3599, -0.6999],
         [-0.4397,  0.0705, -0.2064,  0.5473]]])


In [35]:
#reshaping tensor
# use of function view
# reshape t2 into a row matrix
print(t2.view(1,-1)) # -1 signifies that python will infer the #of rows / cols needed by itself
print(t2.view(1,-1).shape)
# reshape t3_float into a vector
print(t3_float.view(-1,1))
print(t3_float.view(-1,1).shape)
#reshape t5_3d into 2-D shape
print(t5_3d.view(12,2))
print(t5_3d.view(12,2).shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
torch.Size([6, 1])
tensor([[ 2.1491, -1.9523],
        [ 0.5236, -1.2723],
        [ 0.2671,  0.4847],
        [ 0.3938,  1.7444],
        [ 0.0934, -0.4298],
        [ 0.3893,  1.2825],
        [-0.0108, -0.6404],
        [ 1.2542,  1.4042],
        [ 0.3296, -0.2647],
        [-0.3599, -0.6999],
        [-0.4397,  0.0705],
        [-0.2064,  0.5473]])
torch.Size([12, 2])


In [40]:
#rand and randn functions
# rand is used to create matrix of random numbers
#randn is used to create matrix of random numbers with normal distribution , mnean 0
t6_rand = torch.rand(3,2,5)
print(t6_rand)
print(t6_rand.mean())
t7_randn = torch.randn(3,2,5)
print(t7_randn)
print(t7_randn.mean()) # mean nearly 0 and std nearly 1
print(t7_randn.std())  

tensor([[[0.6977, 0.9189, 0.9212, 0.9189, 0.4975],
         [0.6369, 0.7879, 0.9593, 0.2589, 0.3649]],

        [[0.1045, 0.8491, 0.7558, 0.4627, 0.5983],
         [0.6461, 0.3436, 0.3833, 0.6924, 0.8397]],

        [[0.7327, 0.2495, 0.4954, 0.4571, 0.7793],
         [0.4767, 0.7323, 0.6802, 0.0586, 0.8420]]])
tensor(0.6047)
tensor([[[-0.0301,  0.5667,  0.0464,  1.1148,  0.6050],
         [-0.3737, -0.0636, -0.0814, -0.0048,  0.4472]],

        [[-0.7092, -1.4097, -0.1170, -1.0438,  0.3210],
         [ 1.4698, -1.0193, -1.2248, -0.6520, -0.8735]],

        [[-1.0096, -0.4447, -0.2860, -1.2361, -0.2690],
         [ 1.0126, -2.0976, -0.3946,  0.6222, -0.4926]]])
tensor(-0.2542)
tensor(0.8102)


In [47]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
t8_randint=torch.randint(6,10,(5,)) # upper bound exclusive
print(t8_randint)
print(t8_randint.shape)

tensor([8, 9, 7, 8, 6])
torch.Size([5])


In [48]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
t9_randint=torch.randint(6,10,(3,3)) # upper bound exclusive
print(t9_randint)
print(t9_randint.shape)

tensor([[7, 9, 9],
        [9, 6, 8],
        [7, 6, 9]])
torch.Size([3, 3])


In [50]:
#Get the number of elemetns in in_array
print(torch.numel(t8_randint))
#Get the number of elemetns in in_array2
print(torch.numel(t9_randint))

5
9


In [53]:
#Construct a 3x3 matrix of zeros and of dtype long:
t10_zeros = torch.zeros((3,3),dtype=torch.long)
print(t10_zeros)
print(t10_zeros.shape)
#Construct a 3x3 matrix of ones
t11_ones = torch.ones((3,3))
print(t11_ones)
print(t11_ones.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


In [58]:
#create a tensor of another tensor's shape but different datatype
t12_double = torch.randn_like(t3_float,dtype=torch.double)
print(t12_double)
print(t12_double.shape)
print(t3_float)
print(t3_float.shape)
#while creating int type tensor from float type encountered error
# RuntimeError: _th_normal_ not supported on CPUType for Int

tensor([[ 0.6253,  0.5343, -1.0776],
        [ 0.0133,  1.5922, -0.3261]], dtype=torch.float64)
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [59]:
#Add two tensors, make sure they are the same size and data type
t13_add = t3_float + t12_double
print(t13_add)
print(t13_add.dtype)
t13_add = torch.add(t3_float,t12_double)
print(t13_add)
print(t13_add.dtype)

tensor([[1.6253, 2.5343, 1.9224],
        [4.0133, 6.5922, 5.6739]], dtype=torch.float64)
torch.float64
tensor([[1.6253, 2.5343, 1.9224],
        [4.0133, 6.5922, 5.6739]], dtype=torch.float64)
torch.float64


In [60]:
#inplace addition
t12_double.add_(t3_float)
print(t12_double)
print(t12_double.shape)

tensor([[1.6253, 2.5343, 1.9224],
        [4.0133, 6.5922, 5.6739]], dtype=torch.float64)
torch.Size([2, 3])


In [73]:
#selecting data from tensor/ slicing an array
print(t12_double.shape)
#print first row and first 2 colunms 
print(t12_double[1,:2]) #forward indexing
print(t12_double[1,-3:-1]) # reverse indexing
#print all rows  and last columns
print(t12_double[:,-1])
print(t12_double[:,2])
#printing the item in the tensor
#print the 5th element of the tensor
print(t12_double[1,1].item()) # remeber in tensor index starts with 0 not 1 

torch.Size([2, 3])
tensor([4.0133, 6.5922], dtype=torch.float64)
tensor([4.0133, 6.5922], dtype=torch.float64)
tensor([1.9224, 5.6739], dtype=torch.float64)
tensor([1.9224, 5.6739], dtype=torch.float64)
6.592206301363558


# Numpy Bridge

In [74]:
#import numpy package 
import numpy as np

In [84]:
# converting one torch tensor into numpy array
t14_torch = torch.ones(3,4)
arr1_np = t14_torch.numpy()
print(type(t14_torch))
print(type(arr1_np))
# impact of the inplace operation
t14_torch.add_(2)
print((t14_torch))
print((arr1_np))
#impact of normal addition 
t14_torch = t14_torch + 2
print((t14_torch))
print((arr1_np))
# since the inplace addition is impacting both we need to use it carefully

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [85]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a=np.ones([5,5])
print(a)
b=torch.from_numpy(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)
a=a+1
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)


In [86]:
#You can also convert a list to a tensor
a=[2,3,4,5]
print(a)
to_list=torch.tensor(a)
print(to_list)

[2, 3, 4, 5]
tensor([2, 3, 4, 5])


In [87]:
#convert tuple into a tensor
data=([2,3],[3,4],[4,5])
print(type(data))
to_tensor=torch.tensor(data)
print(to_tensor)

<class 'tuple'>
tensor([[2, 3],
        [3, 4],
        [4, 5]])


# Tensor concatenation 

In [92]:
# concat along dim = 0 or rows 
t15_concat = torch.randn(3,5)
t16_concat = torch.randn(2,5)
t17_concat = torch.cat([t15_concat,t16_concat],axis = 0)
print('\n concatenating along 0 dim or rows')
print(t17_concat.shape)
# concat along dim = 1 or cols
t18_concat = torch.randn(2,2)
t19_concat = torch.randn(2,3)
t20_concat = torch.cat([t18_concat,t19_concat],axis = 1)
print('\n concatenating along 1 dim or cols')
print(t20_concat.shape)

torch.Size([5, 5])
torch.Size([2, 5])


# Adding dimensions to tensor

In [93]:
#adding dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
print(tensor_1.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
torch.Size([4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [94]:
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
tensor_c = tensor_2[:,:,2] # selecting column 3 for both channels
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[[0.7112, 0.5636, 0.3821, 0.0331],
         [0.6510, 0.9916, 0.5151, 0.8145],
         [0.1329, 0.7640, 0.7334, 0.0437]],

        [[0.4863, 0.8903, 0.9182, 0.6826],
         [0.8329, 0.4130, 0.3873, 0.0187],
         [0.3849, 0.4522, 0.1472, 0.9908]]])
tensor([[0.3821, 0.5151, 0.7334],
        [0.9182, 0.3873, 0.1472]])
torch.Size([2, 3])


tensor([[[0.3821],
         [0.5151],
         [0.7334]],

        [[0.9182],
         [0.3873],
         [0.1472]]])
torch.Size([2, 3, 1])


# Autograd

In [112]:
#if we want to calculate the derivative w.r.t one element we need to select requires_grad = True
# by default the requires_grad = False
# important : if you select this for tensor of type int then will throw below error\
# RuntimeError: Only Tensors of floating point dtype can require gradients
#example
x = torch.tensor([[1.,2,3],[3,4,5]],requires_grad=True)
y = torch.tensor([[6,7.,8],[9,10,11]],requires_grad=True)
z = x+y
a = torch.sum(torch.tanh(z))
print(z)
print(a)
a.backward()
print(a.grad)
print(z.grad)
print(x.grad)
print(y.grad)

# # we can calculate gradient of scaler only
# that means the final o/p should be a scaler quantity
# also the grad will not calculate values for intermediate variables
# like here if you see the a.grad and z.grad it will show None
# It will only show values for x.grad and y.grad


tensor([[ 7.,  9., 11.],
        [12., 14., 16.]], grad_fn=<AddBackward0>)
tensor(6.0000, grad_fn=<SumBackward0>)
None
None
tensor([[3.3379e-06, 1.1921e-07, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[3.3379e-06, 1.1921e-07, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [113]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False
